[build]
  command  = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  publish  = "public"

  [build.environment]              # <-- indentation is critical
    HUGO_VERSION       = "0.122.0" # last Wowchemy-safe release
    HUGO_ENV           = "production"
    HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
